export const MULTIVERSE_ABI = [{"type":"function","name":"combine","inputs":[{"name":"asset","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"create","inputs":[{"name":"asset","type":"address","internalType":"address"},{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"yesVerse","type":"address","internalType":"address"},{"name":"noVerse","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},{"type":"function","name":"getVerseAddress","inputs":[{"name":"asset","type":"address","internalType":"address"},{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"yesVerse","type":"address","internalType":"address"},{"name":"noVerse","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"isVerse","inputs":[{"name":"verse","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},{"type":"function","name":"markets","inputs":[{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"resolutionDeadline","type":"uint32","internalType":"uint32"},{"name":"oracle","type":"address","internalType":"address"},{"name":"questionHash","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},{"type":"function","name":"open","inputs":[{"name":"questionHash","type":"bytes32","internalType":"bytes32"},{"name":"resolutionDeadline","type":"uint32","internalType":"uint32"},{"name":"oracle","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"redeem","inputs":[{"name":"verse","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"redeemedAmount","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},{"type":"function","name":"resolutions","inputs":[{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"uint8","internalType":"enum MultiVerse.Resolution"}],"stateMutability":"view"},{"type":"function","name":"resolve","inputs":[{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"split","inputs":[{"name":"asset","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"marketHash","type":"bytes32","internalType":"bytes32"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"error","name":"InvalidMarketState","inputs":[]},{"type":"error","name":"InvalidResolution","inputs":[]},{"type":"error","name":"InvalidVerse","inputs":[]},{"type":"error","name":"MarketAlreadyOpened","inputs":[]}] as const;

export const UNISWAP_V2_PAIR_ABI = [{"type":"function","name":"allowance","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"spender","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"approve","inputs":[{"name":"spender","type":"address","internalType":"address"},{"name":"value","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"},{"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"getReserves","inputs":[],"outputs":[{"name":"reserve0","type":"uint112","internalType":"uint112"},{"name":"reserve1","type":"uint112","internalType":"uint112"},{"name":"blockTimestampLast","type":"uint32","internalType":"uint32"}],"stateMutability":"view"},{"type":"function","name":"swap","inputs":[{"name":"amount0Out","type":"uint256","internalType":"uint256"},{"name":"amount1Out","type":"uint256","internalType":"uint256"},{"name":"to","type":"address","internalType":"address"},{"name":"data","type":"bytes","internalType":"bytes"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"token0","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"token1","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},{"type":"function","name":"transfer","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"value","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"},{"type":"function","name":"transferFrom","inputs":[{"name":"from","type":"address","internalType":"address"},{"name":"to","type":"address","internalType":"address"},{"name":"value","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"}] as const;

export const ERC20_ABI = [{"type":"function","name":"allowance","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"spender","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"approve","inputs":[{"name":"spender","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"},{"type":"function","name":"balanceOf","inputs":[{"name":"account","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"decimals","inputs":[],"outputs":[{"name":"","type":"uint8","internalType":"uint8"}],"stateMutability":"view"},{"type":"function","name":"name","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"symbol","inputs":[],"outputs":[{"name":"","type":"string","internalType":"string"}],"stateMutability":"view"},{"type":"function","name":"totalSupply","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},{"type":"function","name":"transfer","inputs":[{"name":"to","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"},{"type":"function","name":"transferFrom","inputs":[{"name":"from","type":"address","internalType":"address"},{"name":"to","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"nonpayable"}] as const;

// Contract addresses for Base Sepolia
export const CONTRACTS = {
  MULTIVERSE: '0x0000000000000000000000000000000000000000', // TODO: Replace with deployed address
  WETH: '0x4200000000000000000000000000000000000006', // WETH on Base Sepolia
  USDC: '0x036CbD53842c5426634e7929541eC2318f3dCF7e', // USDC on Base Sepolia
  UNISWAP_V2_FACTORY: '0x0000000000000000000000000000000000000000', // TODO: Replace with deployed address
  UNISWAP_V2_ROUTER: '0x0000000000000000000000000000000000000000', // TODO: Replace with deployed address
} as const;

// Mock markets for development - replace with actual market data
export const MOCK_MARKETS = [
  {
    questionHash: '0x1234567890123456789012345678901234567890123456789012345678901234',
    marketHash: '0xabcdef1234567890123456789012345678901234567890123456789012345678',
    question: 'Will FOCIL be included in the Ethereum Glamsterdam hardfork?',
    resolutionDeadline: 1735689600, // Jan 1, 2025
    oracle: '0x0000000000000000000000000000000000000000',
  },
  {
    questionHash: '0x2345678901234567890123456789012345678901234567890123456789012345',
    marketHash: '0xbcdef12345678901234567890123456789012345678901234567890123456789',
    question: 'Will ETH price exceed $5000 by end of 2025?',
    resolutionDeadline: 1735689600,
    oracle: '0x0000000000000000000000000000000000000000',
  },
];

export type Market = typeof MOCK_MARKETS[0];