#![allow(unused_imports, unused_attributes, dead_code, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#deploy_multi_verse;
pub mod r#multi_verse_test;
pub mod r#multi_verse;
pub mod r#trusted_oracle;
pub mod r#verse;
pub mod r#verse_amm_test;
pub mod r#verse_test;
